[package]
name = "bubbles"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gif = "0.11.4"
rand = "0.8.5"
clap = { version = "3.2.17", features = ["derive"]}
